export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const POST_PRODUCT_REQUEST = "POST_PRODUCT_REQUEST"
export const PUT_PRODUCT_REQUEST = "PUT_PRODUCT_REQUEST"
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_FAILED = "PRODUCT_FAILED"


export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

